### ISSUE TITLE
Code completition selection when selecting with keyboard is barely visible.

### ISSUE THREAD

**Issue by jtiai** [KYDronePilot/material-deep-ocean-theme#2]
![image](https://user-images.githubusercontent.com/1370289/137772164-62e9c788-60da-4d79-ab7f-cd2f8d59cab4.png)

Like in image above, second row is selected.

Mouse hover is more visible:

![image](https://user-images.githubusercontent.com/1370289/137772313-1f9c7f35-5c95-4e30-b4cd-d99f74648dc0.png)

**Comment by KYDronePilot** [comment]
Fixed in version `0.0.4` (56ced82) so they are the same color.

Also used a slightly darker color for both so it's more visible.
